name=MT_BoardOrientation
version=0.2.0
author=mattThurstan
maintainer=mattThurstan
sentence=Orientation setup library for long/short/skate boards.
paragraph=Give it IMU data. Used in mattThurstan/longboardLight1 project.
category=Sensors
url=https://github.com/mattThurstan/MT_BoardOrientation
includes=MT_BoardOrientation.h